"""empty message

Revision ID: 5d903b0156dc
Revises: b1c44fd97bab
Create Date: 2021-03-29 09:27:24.895966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d903b0156dc'
down_revision = 'b1c44fd97bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # ### end Alembic commands ###
    op.execute('update todolists set completed = False where completed is null;')

    op.alter_column('todolists', 'completed', nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
